In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import model_selection

In [2]:
dataset_path = 'perfume_type_classification_dataset.csv'

In [3]:
df = pd.read_csv(dataset_path)
df

,longevity_hours,sillage_score,top_note_count,price_usd,concentration_percent,fragrance_family,brand_tier,gender_target,contains_alcohol,limited_edition,perfume_category
0,5.96,5.80,5,103.71,17.04,Floral,Designer,Men,0.0,0,Eau de Parfum
1,8.85,7.70,4,122.93,15.28,Oriental,Luxury,Men,1.0,0,Eau de Toilette
2,0.54,2.67,3,105.21,12.69,Fresh,Designer,Men,0.0,0,Eau de Toilette
3,9.83,8.06,7,165.64,20.95,Floral,Luxury,Women,1.0,0,Eau de Parfum
4,11.03,9.72,5,279.00,25.00,Oriental,Luxury,Women,1.0,0,Perfume Extract
...,...,...,...,...,...,...,...,...,...,...,...
69995,8.29,7.82,6,67.13,7.61,Citrus,Luxury,Men,1.0,0,Eau de Toilette
69996,5.92,3.82,6,71.81,11.16,Oriental,Niche,Women,1.0,0,Eau de Toilette
69997,7.55,5.13,5,23.56,18.84,Citrus,Drugstore,Women,1.0,0,Eau de Parfum
69998,3.09,7.37,5,71.07,21.56,Fresh,Drugstore,Men,1.0,0,Eau de Parfum
69999,0.50,5.81,9,22.27,11.32,Woody,Luxury,Women,1.0,0,Eau de Toilette

|name   | description|
|-------|------------|
|longevity_hours	|	How long the scent lasts|
|sillage_score	|	Scent trail/projection strength (1–10)|
|top_note_count	|	Number of top notes (fewer in stronger concentrations)|
|price_usd	|	Retail price|
|concentration_percent	|	Fragrance oil concentration (%)|
|fragrance_family	|	Floral / Woody / Oriental / Fresh / Citrus|
|brand_tier	|	Luxury / Designer / Niche / Drugstore|
|gender_target	|	Men / Women / Unisex|
|contains_alcohol	|	0/1 yes or no|
|limited_edition	|	0/1 yes or no|
|perfume_category	|	Eau de Cologne / Eau de Toilette / Eau de Parfum / Perfume Extract|

As we can see our dataset has 70k rows and 10 features as well as one target feature - perfume_category

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   longevity_hours        70000 non-null  float64
 1   sillage_score          70000 non-null  float64
 2   top_note_count         70000 non-null  int64
 3   price_usd              69272 non-null  float64
 4   concentration_percent  70000 non-null  float64
 5   fragrance_family       70000 non-null  object
 6   brand_tier             66497 non-null  object
 7   gender_target          70000 non-null  object
 8   contains_alcohol       68251 non-null  float64
 9   limited_edition        70000 non-null  int64
 10  perfume_category       70000 non-null  object
dtypes: float64(5), int64(2), object(4)
memory usage: 5.9+ MB

In [5]:
df.duplicated().sum()

np.int64(15000)

As we can see there are some null values we need to fix. Also we should encode the categorical values and drop duplicate rows.

In [6]:
df = df.drop_duplicates()
df

,longevity_hours,sillage_score,top_note_count,price_usd,concentration_percent,fragrance_family,brand_tier,gender_target,contains_alcohol,limited_edition,perfume_category
0,5.96,5.80,5,103.71,17.04,Floral,Designer,Men,0.0,0,Eau de Parfum
1,8.85,7.70,4,122.93,15.28,Oriental,Luxury,Men,1.0,0,Eau de Toilette
2,0.54,2.67,3,105.21,12.69,Fresh,Designer,Men,0.0,0,Eau de Toilette
3,9.83,8.06,7,165.64,20.95,Floral,Luxury,Women,1.0,0,Eau de Parfum
4,11.03,9.72,5,279.00,25.00,Oriental,Luxury,Women,1.0,0,Perfume Extract
...,...,...,...,...,...,...,...,...,...,...,...
69994,7.82,6.87,9,126.94,7.58,Oriental,Luxury,Men,1.0,1,Eau de Parfum
69995,8.29,7.82,6,67.13,7.61,Citrus,Luxury,Men,1.0,0,Eau de Toilette
69996,5.92,3.82,6,71.81,11.16,Oriental,Niche,Women,1.0,0,Eau de Toilette
69997,7.55,5.13,5,23.56,18.84,Citrus,Drugstore,Women,1.0,0,Eau de Parfum
69998,3.09,7.37,5,71.07,21.56,Fresh,Drugstore,Men,1.0,0,Eau de Parfum